import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import Header from "@/components/Header"
import PageTransition from "@/components/PageTransition"
import StairTransition from "@/components/StairTransition"

const jetBrainsMono = localFont({
  src: "./fonts/JetBrainsMono.woff",
  variable: "--font-jetbrainsMono",
  weight: "500",
})

export const metadata: Metadata = {
  title: "Muhammad Ishaq",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${jetBrainsMono.variable} overflow-hidden`}>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  )
}
